p8105_hw3_rd3096
================

# load necessary pakages

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(ggridges)
library(patchwork)
library(ggplot2)

library(p8105.datasets)
data("ny_noaa")

knitr::opts_chunk$set(
    echo = TRUE,
    warning = FALSE,
    fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## problem 1

### read and explore the dataset “ny_noaa”

we explore the dataset and get a summary of the dataset

``` r
str(ny_noaa)
```

    ## tibble [2,595,176 × 7] (S3: tbl_df/tbl/data.frame)
    ##  $ id  : chr [1:2595176] "US1NYAB0001" "US1NYAB0001" "US1NYAB0001" "US1NYAB0001" ...
    ##  $ date: Date[1:2595176], format: "2007-11-01" "2007-11-02" ...
    ##  $ prcp: int [1:2595176] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ snow: int [1:2595176] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ snwd: int [1:2595176] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ tmax: chr [1:2595176] NA NA NA NA ...
    ##  $ tmin: chr [1:2595176] NA NA NA NA ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   id = col_character(),
    ##   ..   date = col_date(format = ""),
    ##   ..   prcp = col_integer(),
    ##   ..   snow = col_integer(),
    ##   ..   snwd = col_integer(),
    ##   ..   tmax = col_character(),
    ##   ..   tmin = col_character()
    ##   .. )

``` r
summary(ny_noaa)
```

    ##       id                 date                 prcp               snow       
    ##  Length:2595176     Min.   :1981-01-01   Min.   :    0.00   Min.   :  -13   
    ##  Class :character   1st Qu.:1988-11-29   1st Qu.:    0.00   1st Qu.:    0   
    ##  Mode  :character   Median :1997-01-21   Median :    0.00   Median :    0   
    ##                     Mean   :1997-01-01   Mean   :   29.82   Mean   :    5   
    ##                     3rd Qu.:2005-09-01   3rd Qu.:   23.00   3rd Qu.:    0   
    ##                     Max.   :2010-12-31   Max.   :22860.00   Max.   :10160   
    ##                                          NA's   :145838     NA's   :381221  
    ##       snwd            tmax               tmin          
    ##  Min.   :   0.0   Length:2595176     Length:2595176    
    ##  1st Qu.:   0.0   Class :character   Class :character  
    ##  Median :   0.0   Mode  :character   Mode  :character  
    ##  Mean   :  37.3                                        
    ##  3rd Qu.:   0.0                                        
    ##  Max.   :9195.0                                        
    ##  NA's   :591786

### we write a short description of the dataset and answer the following questions

Our dataset ahs 2595176 rows and 7 columns.It includes key variables
such as id (station identifier), date, prcp (precipitation), snow
(snowfall), snwd (snow depth), tmax (maximum temperature), and tmin
(minimum temperature).” The variable types based on our output are
listed as follows:

- id: character

- date: Date format

- prcp, snow, snwd: integer

- tmax, tmin: character (we wil convert these into numeric later for
  proper analysis).

Missing data is a significant issue in the ny_noaa dataset, especially
for snow depth (snwd) and snowfall (snow), Precipitation has less
missing data, but it still affects a non-negligible portion of the
dataset.

we will do some data cleaning for subquestion 1

``` r
ny_noaa_cleaned = 
  ny_noaa %>%
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>%
  mutate(
    tmax = as.numeric(tmax),    
    tmin = as.numeric(tmin)               
  )

ny_noaa_cleaned %>%
  group_by(snow) %>%
  summarize(count = n()) %>%
  arrange(desc(count))
```

    ## # A tibble: 282 × 2
    ##     snow   count
    ##    <int>   <int>
    ##  1     0 2008508
    ##  2    NA  381221
    ##  3    25   31022
    ##  4    13   23095
    ##  5    51   18274
    ##  6    76   10173
    ##  7     8    9962
    ##  8     5    9748
    ##  9    38    9197
    ## 10     3    8790
    ## # ℹ 272 more rows

After we cleaned our dataset, CONVERT the variables into numeric and
count the number of observed values, we found out:

1.  0 mm of snowfall is the most frequently observed value, with
    2,008,508 instances. This is because many days throughout the year
    do not experience snowfall, especially during non-winter months and
    in areas where snow is rare.

2.  There are 381,221 missing values (NA) in the dataset for snowfall.
    These might correspond to missing data for days or locations where
    snowfall was not recorded.

3.  Other common values include 25 mm, 13 mm, and 51 mm of snowfall,
    which likely represent light to moderate snowfall amounts. These
    values are typical during days when snow does occur, especially in
    regions that experience winter weather regularly.

we will make a two-panel plot for subquestion2

``` r
ny_noaa_plot=
  ny_noaa_cleaned %>%
  filter(month %in% c(1, 7)) %>%
  group_by(id, year, month) %>%
  summarize(avg_tmax = mean(tmax, na.rm = TRUE), .groups = 'drop') %>% 
  ggplot(aes(x = year, y = avg_tmax, color = id)) +
  geom_point()+
  geom_line()+
  facet_grid(. ~ month)+
  labs(
      title = "Mean Monthly Temperature for Each Station Across Years (January and July)",
    x = "Year",
    y = "Mean Max Temperature (°C)",
    color = "Station"
  ) +
  theme_minimal()
```
